// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liidiyjforqmmqtqcusx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpaWRpeWpmb3JxbW1xdHFjdXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODc5ODMsImV4cCI6MjA2OTQ2Mzk4M30.5nBtRZ2FD3CYNNYZGlf6fKLer-mR0mLR_043kQtjH9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});